#!/bin/bash
# Generate CA certificate + key and embed as C header
# Run once; commit the generated .h to share same CA across builds
set -euo pipefail

OUTDIR="$(cd "$(dirname "$0")/../src/generated" && pwd)"
mkdir -p "$OUTDIR"

TMP_CERT=$(mktemp)
TMP_KEY=$(mktemp)
trap 'rm -f "$TMP_CERT" "$TMP_KEY"' EXIT

# Generate CA (10 years, CA:TRUE)
# Use a temp config to avoid OpenSSL auto-adding basicConstraints=FALSE
TMP_CONF=$(mktemp)
trap 'rm -f "$TMP_CERT" "$TMP_KEY" "$TMP_CONF"' EXIT
cat > "$TMP_CONF" << 'CONF'
[req]
distinguished_name = req_dn
prompt = no
x509_extensions = ca_ext
[req_dn]
CN = LLM-ROUTER CA
[ca_ext]
basicConstraints = critical,CA:TRUE,pathlen:0
CONF
openssl req -x509 -newkey rsa:2048 -keyout "$TMP_KEY" -out "$TMP_CERT" \
  -days 3650 -nodes -config "$TMP_CONF"

# Convert PEM to C byte array using Python (avoids xxd portability issues)
python3 -c "
import sys
def emit(name, path):
    with open(path, 'rb') as f:
        data = f.read()
    sys.stdout.write(f'static const unsigned char {name}[] = {{\n')
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        sys.stdout.write(' ' + ', '.join(f'0x{b:02x}' for b in chunk) + ',\n')
    sys.stdout.write('};\n')
    sys.stdout.write(f'static const unsigned int {name}_LEN = sizeof({name});\n\n')
sys.stdout.write('#ifndef CA_EMBEDDED_H\n#define CA_EMBEDDED_H\n\n')
sys.stdout.write('/* Auto-generated by scripts/gen-ca.sh - DO NOT EDIT */\n\n')
emit('CA_CERT', '$TMP_CERT')
emit('CA_KEY', '$TMP_KEY')
sys.stdout.write('#endif\n')
" > "$OUTDIR/ca_embedded.h"

echo "Generated $OUTDIR/ca_embedded.h"
